contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.1.25
    packID: Carbon_Black_Enterprise_Response
    packName: Carbon Black Enterprise Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Carbon Black Response - isolates an endpoint for a given hostname.
id: Block Endpoint - Carbon Black Response V2
inputs:
- description: The hostname to isolate.
  key: Hostname
  playbookInputQuery: null
  required: false
  value: {}
- description: The sensor ID of the endpoint.
  key: Sensor_id
  playbookInputQuery: null
  required: false
  value: {}
name: Block Endpoint - Carbon Black Response V2
outputs:
- contextPath: CbResponse.Sensors.CbSensorID
  description: Carbon Black Response Sensors IDs that are isolated.
- contextPath: Endpoint
  description: The isolated endpoint.
- contextPath: CbResponse.Sensors.Status
  description: Sensor status.
  type: unknown
- contextPath: CbResponse.Sensors.Isolated
  description: Is sensor isolated.
  type: unknown
- contextPath: Endpoint.Hostname
  description: Endpoint hostname.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 73040a0e-cca5-4197-8089-f46650317040
      iscommand: false
      name: ""
      version: -1
    taskid: 73040a0e-cca5-4197-8089-f46650317040
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.Hostname}
      sensor:
        simple: ${inputs.Sensor_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Display information about the given sensor.
      id: 8d840b85-2255-4771-8047-1cffd0133d56
      iscommand: true
      name: Get host information from Carbon Black Enterprise Response
      script: '|||cb-sensor-info'
      type: regular
      version: -1
    taskid: 8d840b85-2255-4771-8047-1cffd0133d56
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 530
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      sensor:
        simple: ${CbResponse.Sensors.CbSensorID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Isolate the endpoint from the network.
      id: 8a7b3b07-16d1-4953-897b-dde82b8153f3
      iscommand: true
      name: Isolate endpoint
      script: '|||cb-quarantine-device'
      type: regular
      version: -1
    taskid: 8a7b3b07-16d1-4953-897b-dde82b8153f3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 1165
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d35be2d6-6709-40d0-846e-dc9aef142e30
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d35be2d6-6709-40d0-846e-dc9aef142e30
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1510
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: carbonblack-v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: d338c691-a845-4f21-841e-5482255c63f6
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: d338c691-a845-4f21-841e-5482255c63f6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 210
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CbResponse.Sensors.Isolated
          operator: isEqualString
          right:
            value:
              simple: "false"
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 179cbf36-32ef-47d3-8d77-2bac9a797283
      iscommand: false
      name: 'Is the endpoint ready for isolation? '
      type: condition
      version: -1
    taskid: 179cbf36-32ef-47d3-8d77-2bac9a797283
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -180,
          "y": 735
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "5_4_#default#": 0.79,
      "7_3_yes": 0.64,
      "7_4_#default#": 0.25
    },
    "paper": {
      "dimensions": {
        "height": 1525,
        "width": 722.5,
        "x": -180,
        "y": 50
      }
    }
  }
