contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.2.15
    packID: CrowdStrikeFalconX
    packName: CrowdStrike FalconX
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Detonate one or more files using the CrowdStrike Falcon Sandbox integration.
  This playbook returns relevant reports to the War Room and file reputations to the
  context data.
id: Detonate URL - CrowdStrike Falcon X
inputs:
- description: URL to detonate.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
- description: Environment ID to submit the file to. To get all IDs run the crowdstrike-get-environments
    command.
  key: EnvironmentID
  playbookInputQuery: null
  required: false
  value:
    simple: "100"
- description: Polling frequency - how often the polling command should run (minutes)
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "5"
- description: How much time to wait before a timeout occurs  (minutes)
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "30"
name: Detonate URL - CrowdStrike Falcon X
outputs:
- contextPath: csfalconx.resource.id
  description: Analysis ID.
  type: String
- contextPath: csfalconx.resource.verdict
  description: Analysis verdict.
  type: String
- contextPath: csfalconx.resource.created_timestamp
  description: Analysis start time.
  type: String
- contextPath: csfalconx.resource.environment_id
  description: Environment ID.
  type: String
- contextPath: csfalconx.resource.environment_description
  description: Environment description.
  type: String
- contextPath: csfalconx.resource.threat_score
  description: Score of the threat.
  type: Int
- contextPath: csfalconx.resource.submit_url
  description: URL submitted for analysis.
  type: String
- contextPath: csfalconx.resource.submission_type
  description: Type of submitted artifact, for example file, URL, etc.
  type: String
- contextPath: csfalconx.resource.sha256
  description: SHA256 hash of the submitted file.
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_csv_artifact_id
  description: ID of the IOC pack to download (CSV).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_csv_artifact_id
  description: ID of the IOC pack to download (CSV).
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_json_artifact_id
  description: ID of the IOC pack to download (JSON).
  type: Int
- contextPath: csfalconx.resource.ioc_report_broad_json_artifact_id
  description: ID of the IOC pack to download (JSON).
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_stix_artifact_id
  description: ID of the IOC pack to download (STIX).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_stix_artifact_id
  description: ID of the IOC pack to download (STIX).
  type: Int
- contextPath: csfalconx.resource.ioc_report_strict_maec_artifact_id
  description: ID of the IOC pack to download (MAEC).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_maec_artifact_id
  description: ID of the IOC pack to download (MAEC).
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5efceda5-4236-42ed-882f-e26acb6f4756
      iscommand: false
      name: ""
      version: -1
    taskid: 5efceda5-4236-42ed-882f-e26acb6f4756
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 0
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: CrowdStrike Falcon X
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verify that there is a valid instance of CrowdStrike enabled.
      id: fc1f205f-4605-402d-805d-57b7d4b4cef7
      iscommand: false
      name: Is CrowdStrike Falcon X enabled?
      type: condition
      version: -1
    taskid: fc1f205f-4605-402d-805d-57b7d4b4cef7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 165
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: 66063116-5734-4166-82b3-aa4c0f629285
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 66063116-5734-4166-82b3-aa4c0f629285
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1140
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${csfalconx.resource.submitted_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CrowdStrike Falcon X
      description: Get a full version of a sandbox report.
      id: 9ab16bf8-de8e-4201-8561-992345b51280
      iscommand: true
      name: CrowdStrike Falcon X Get Report
      script: CrowdStrike Falcon X|||cs-fx-get-full-report
      type: regular
      version: -1
    taskid: 9ab16bf8-de8e-4201-8561-992345b51280
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 935
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      environment_id:
        simple: '160: Windows 10'
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Submit a URL or FTP for sandbox analysis.
      id: 251b7acf-b9ad-4122-8968-788528be9bc1
      iscommand: true
      name: CrowdStrike Falcon X Submit URL
      script: '|||cs-fx-submit-url'
      type: regular
      version: -1
    taskid: 251b7acf-b9ad-4122-8968-788528be9bc1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 590
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there's a file to detonate.
      id: 7bda06fb-0f5a-487b-8242-69d776363760
      iscommand: false
      name: Is there a URL to detonate?
      type: condition
      version: -1
    taskid: 7bda06fb-0f5a-487b-8242-69d776363760
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 380
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: resource.submitted_id
          root: csfalconx
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: ids
      PollingCommandName:
        simple: cs-fx-get-analysis-status
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: csfalconx(val.resource.state !== 'success').resource.id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 92f6cd66-9c00-4782-85e6-4b9ebe0fd014
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 92f6cd66-9c00-4782-85e6-4b9ebe0fd014
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 760
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1205,
        "width": 677.5,
        "x": 162.5,
        "y": 0
      }
    }
  }
