contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.1.25
    packID: Carbon_Black_Enterprise_Response
    packName: Carbon Black Enterprise Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Returns a file sample to the war-room from a path on an endpoint using
  Carbon Black Enterprise Response
id: get_file_sample_from_path_-_carbon_black_enterprise_response
inputs:
- description: The host to get file from
  key: Hostname
  playbookInputQuery: null
  required: false
  value:
    simple: ${Endpoint.Hostname}
- description: Path of the file on the endpoint
  key: Path
  playbookInputQuery: null
  required: false
  value:
    simple: ${File.Path}
name: Get File Sample From Path - Carbon Black Enterprise Response
outputs:
- contextPath: CbLiveResponse.Commands.CbCommandID
  description: Unique command identifier.
  type: Number
- contextPath: CbLiveResponse.Commands.CommandName
  description: The command name.
  type: String
- contextPath: CbLiveResponse.Commands.Status
  description: The command status ('pending', 'in progress', 'complete', 'error',
    or 'canceled').
  type: String
- contextPath: CbLiveResponse.Commands.CommandCompletionTime
  description: The command completion time (0 if not complete).
  type: String
- contextPath: CbLiveResponse.Commands.OperandObject
  description: The source path of the file.
  type: String
- contextPath: CbLiveResponse.Commands.FileID
  description: Unique file ID.
  type: Number
- contextPath: CbLiveResponse.File.Size
  description: File size.
  type: String
- contextPath: CbLiveResponse.File.SHA1
  description: File SHA1 hash.
  type: String
- contextPath: CbLiveResponse.File.SHA256
  description: File SHA256 hash.
  type: String
- contextPath: CbLiveResponse.File.Name
  description: File name.
  type: String
- contextPath: CbLiveResponse.File.SSDeep
  description: File SSDeep hash.
  type: String
- contextPath: CbLiveResponse.File.EntryID
  description: File EntryID.
  type: Number
- contextPath: CbLiveResponse.File.Info
  description: File info.
  type: String
- contextPath: CbLiveResponse.File.Type
  description: File type.
  type: String
- contextPath: CbLiveResponse.File.MD5
  description: File MD5.
  type: String
- contextPath: CbLiveResponse.File.Extension
  description: File extension.
  type: String
- contextPath: File.Size
  description: The size of the file in bytes.
  type: Number
- contextPath: File.MD5
  description: The MD5 hash of the file.
  type: String
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: String
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
  type: String
- contextPath: File.Name
  description: The name of the file.
  type: String
- contextPath: File.SSDeep
  description: The SSDeep hash of the file (same as displayed in file entries).
  type: String
- contextPath: File.EntryID
  description: File entry ID.
  type: String
- contextPath: File.Info
  description: Information about the file.
  type: String
- contextPath: File.Type
  description: The file type.
  type: String
- contextPath: File.Extension
  description: The extension of the file.
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6b09e12d-a699-4b98-8f93-0ee2fb3904df
      iscommand: false
      name: ""
      version: -1
    taskid: 6b09e12d-a699-4b98-8f93-0ee2fb3904df
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 48
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: isEqualString
              right:
                value:
                  simple: carbonblack
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if  Carbon Black Enterprise Response active in the system.
      id: 40ec070b-2ab3-432a-86fa-eb02b381398a
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      script: Exists
      type: condition
      version: -1
    taskid: 40ec070b-2ab3-432a-86fa-eb02b381398a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 196
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 347006fd-60f5-4233-8c40-9b941735dd2a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 347006fd-60f5-4233-8c40-9b941735dd2a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint:
        simple: ${inputs.Hostname}
      path:
        simple: ${inputs.Path}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Use Carbon black Response Live session to retrieve a file from
        an endpoint. Endpoint needs to have a CbResponse sensor deployed.
      id: 6361a341-4a5c-4735-8ffe-ce13d9539b91
      iscommand: false
      name: Get File
      script: CBLiveGetFile_V2
      type: regular
      version: -1
    taskid: 6361a341-4a5c-4735-8ffe-ce13d9539b91
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 514,
          "y": 544
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Path
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${inputs.Path}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if a file path exists in playbook inputs.
      id: 69aeb053-04ea-4853-872a-adf410c08c5e
      iscommand: false
      name: Is there a file path and hostname?
      type: condition
      version: -1
    taskid: 69aeb053-04ea-4853-872a-adf410c08c5e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 301,
          "y": 367
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "1_3_#default#": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 737,
        "width": 844,
        "x": 50,
        "y": 48
      }
    }
  }
