contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.2.15
    packID: CrowdStrikeFalconX
    packName: CrowdStrike FalconX
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: |-
  Detonates a File using CrowdStrike Falcon X sandbox.
  Accepted file formats:
  Portable executables: .exe, .scr, .pif, .dll, .com, .cpl, etc.
  Office documents: .doc, .docx, .ppt, .pps, .pptx, .ppsx, .xls, .xlsx, .rtf, .pub
  PDF
  APK
  Executable JAR
  Windows script component: .sct
  Windows shortcut: .lnk
  Windows help: .chm
  HTML application: .hta
  Windows script file: .wsf
  Javascript: .js
  Visual Basic: .vbs, .vbe
  Shockwave Flash: .swf
  Perl: .pl
  Powershell: .ps1, .psd1, .psm1
  Scalable vector graphics: .svg
  Python: .py
  Linux ELF executables
  Email files: MIME RFC 822 .eml, Outlook .msg.
id: Detonate File - CrowdStrike Falcon X
inputs:
- description: The file to detonate. The file is taken from the context.
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
- description: Polling frequency - how often the polling command should run (minutes)
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: How much time to wait before a timeout occurs (minutes)
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "15"
- description: Whether the sandbox analysis routes network traffic via TOR. If true,
    sandbox analysis routes network traffic via TOR. Relevant if the submit_file parameter
    is set to true.
  key: EnableTor
  playbookInputQuery: null
  required: false
  value:
    simple: "false"
- description: Sandbox environment used for analysis.
  key: EnvironmentID
  playbookInputQuery: null
  required: false
  value:
    simple: '160: Windows 10'
- description: Runtime script for sandbox analysis.
  key: ActionScript
  playbookInputQuery: null
  required: false
  value: {}
- description: 'Command line script passed to the submitted file at runtime. Max length:
    2048 characters.'
  key: CommandLine
  playbookInputQuery: null
  required: false
  value: {}
- description: 'Auto-filled for Adobe or Office files that prompt for a password.
    Max length: 32 characters.'
  key: DocumentPassword
  playbookInputQuery: null
  required: false
  value: {}
- description: Name of the malware sample that’s used for file type detection. and
    analysis.
  key: SubmitName
  playbookInputQuery: null
  required: false
  value: {}
- description: Set a custom date for the sandbox environment in the format yyyy-MM-dd.
  key: SystemDate
  playbookInputQuery: null
  required: false
  value: {}
- description: Sets a custom time for the sandbox environment in the format HH:mm.
  key: SystemTime
  playbookInputQuery: null
  required: false
  value: {}
name: Detonate File - CrowdStrike Falcon X
outputs:
- contextPath: csfalconx.resource.id
  description: Analysis ID.
  type: String
- contextPath: csfalconx.resource.verdict
  description: Analysis verdict.
  type: String
- contextPath: csfalconx.resource.created_timestamp
  description: Analysis start time.
  type: String
- contextPath: csfalconx.resource.environment_id
  description: Environment ID.
  type: String
- contextPath: csfalconx.resource.snadbox.environment_description
  description: Environment description.
  type: String
- contextPath: csfalconx.resource.threat_score
  description: Score of the threat.
  type: Int
- contextPath: csfalconx.resource.submit_url
  description: URL submitted for analysis.
  type: String
- contextPath: csfalconx.resource.submission_type
  description: Type of submitted artifact, for example file, URL, etc.
  type: String
- contextPath: csfalconx.resource.filetype
  description: File type.
  type: String
- contextPath: csfalconx.resource.filesize
  description: File size.
  type: Int
- contextPath: csfalconx.resource.sha256
  description: SHA256 hash of the submitted file.
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_csv_artifact_id
  description: ID of the IOC pack to download (CSV).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_csv_artifact_id
  description: ID of the IOC pack to download (CSV).
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_json_artifact_id
  description: ID of the IOC pack to download (JSON).
  type: Int
- contextPath: csfalconx.resource.ioc_report_broad_json_artifact_id
  description: ID of the IOC pack to download (JSON).
  type: String
- contextPath: csfalconx.resource.ioc_report_strict_stix_artifact_id
  description: ID of the IOC pack to download (STIX).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_stix_artifact_id
  description: ID of the IOC pack to download (STIX).
  type: Int
- contextPath: csfalconx.resource.ioc_report_strict_maec_artifact_id
  description: ID of the IOC pack to download (MAEC).
  type: String
- contextPath: csfalconx.resource.ioc_report_broad_maec_artifact_id
  description: ID of the IOC pack to download (MAEC).
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 2e14779f-7f47-4445-845c-bfea5627cbe3
      iscommand: false
      name: ""
      version: -1
    taskid: 2e14779f-7f47-4445-845c-bfea5627cbe3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 20
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: resource.submitted_id
          root: csfalconx
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: ids
      PollingCommandName:
        simple: cs-fx-get-analysis-status
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: csfalconx(val.resource.state !== 'success').resource.id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 334792b6-7e5d-4494-85a1-aa4bc2274105
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 334792b6-7e5d-4494-85a1-aa4bc2274105
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1530
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${csfalconx.resource.submitted_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CrowdStrike Falcon X
      description: Get a full version of a sandbox report.
      id: c7c659db-15a7-4c9b-8f3d-72713eefe5f1
      iscommand: true
      name: CrowdStrike Falcon X Get Report
      script: CrowdStrike Falcon X|||cs-fx-get-full-report
      type: regular
      version: -1
    taskid: c7c659db-15a7-4c9b-8f3d-72713eefe5f1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1760
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: finished
      id: 73843b9d-b556-4e1c-895c-93ae4f6671dc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 73843b9d-b556-4e1c-895c-93ae4f6671dc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 70,
          "y": 2090
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: CrowdStrike Falcon X
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verify that there is a valid instance of CrowdStrike Falcon X enabled.
      id: ee402758-5d33-4edd-89fb-816dee6233c5
      iscommand: false
      name: Is CrowdStrike Falcon X enabled?
      type: condition
      version: -1
    taskid: ee402758-5d33-4edd-89fb-816dee6233c5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: csfalconx.resource.submitted_id(val != -1)
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks that only valid files have been sent to detonation.
      id: 44e9c26f-c38e-4c1c-8b60-80a92220810e
      iscommand: false
      name: Filter taskId
      type: condition
      version: -1
    taskid: 44e9c26f-c38e-4c1c-8b60-80a92220810e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1230
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|DLL|COM|SCR|CPL|DOC|DOCX|XLS|XSLX|PPS|PPSX|PPT|PPTX|RTF|PDF|ETC|PUB|SCT|INK|CHM|HTA|WSF|JS|VBS|VBE|SWF|PL|PS1|PSD1|PSM1|SVG|PY|ELF|EML|MSG)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|DLL|COM|SCR|CPL|DOC|DOCX|XLS|XSLX|PPS|PPSX|PPT|PPTX|RTF|PDF|ETC|PUB|SCT|INK|CHM|HTA|WSF|JS|VBS|VBE|SWF|PL|PS1|PSD1|PSM1|SVG|PY|ELF|EML|MSG)\b
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: match
                    right:
                      value:
                        simple: .*(?:EXE|DLL|COM|SCR|CPL|DOC|DOCX|XLS|XSLX|PPS|PPSX|PPT|PPTX|RTF|PDF|ETC|PUB|SCT|INK|CHM|HTA|WSF|JS|VBS|VBE|SWF|PL|PS1|PSD1|PSM1|SVG|PY|ELF|EML|MSG)\b
                root: File
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the file type is supported.
      id: dd7a0c59-4cf4-4a46-8316-19dadac61a1b
      iscommand: false
      name: Is file type supported?
      type: condition
      version: -1
    taskid: dd7a0c59-4cf4-4a46-8316-19dadac61a1b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: File
      value:
        complex:
          root: inputs.File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set the file object into context.
      id: e0e4b29f-fe26-47b2-8930-00d6087bdbeb
      iscommand: false
      name: Set File to context
      script: Set
      type: regular
      version: -1
    taskid: e0e4b29f-fe26-47b2-8930-00d6087bdbeb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.File
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks that there is a file in the playbook’s input.
      id: 813639b9-9c78-44dc-8600-afad5cc1c5db
      iscommand: false
      name: Is there a File to Detonate?
      type: condition
      version: -1
    taskid: 813639b9-9c78-44dc-8600-afad5cc1c5db
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      action_script:
        simple: ${inputs.ActionScript}
      command_line:
        simple: ${inputs.CommandLine}
      document_password:
        simple: ${inputs.DocumentPassword}
      enable_tor:
        simple: "false"
      environment_id:
        simple: ${inputs.EnvironmentID}
      file:
        simple: ${inputs.File.EntryID}
      file_name:
        simple: ${inputs.File.Name}
      sha256:
        simple: ${csfalconx.resource.sha256}
      submit_name:
        simple: ${inputs.SubmitName}
      system_date:
        simple: ${inputs.SystemDate}
      system_time:
        simple: ${inputs.SystemTime}
    separatecontext: false
    skipunavailable: false
    task:
      brand: CrowdStrike Falcon X
      description: Upload a file for sandbox analysis.
      id: 33e04243-7824-4475-8ea1-5c2366c22fd6
      iscommand: true
      name: CrowdStrike Falcon X Upload File to Sandbox
      script: CrowdStrike Falcon X|||cs-fx-upload-file
      type: regular
      version: -1
    taskid: 33e04243-7824-4475-8ea1-5c2366c22fd6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 915
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      action_script:
        simple: ${inputs.ActionScript}
      command_line:
        simple: ${inputs.CommandLine}
      document_password:
        simple: ${inputs.DocumentPassword}
      enable_tor:
        simple: "false"
      environment_id:
        simple: ${inputs.EnvironmentID}
      sha256:
        simple: ${csfalconx.resource.sha256}
      submit_name:
        simple: ${inputs.SubmitName}
      system_date:
        simple: ${inputs.SystemDate}
      system_time:
        simple: ${inputs.SystemTime}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Submit a sample SHA256 for sandbox analysis.
      id: 5a968f27-55f8-4761-88d0-a89b4d023bda
      iscommand: true
      name: CrowdStrike FalconX Detonate Uploaded File
      script: '|||cs-fx-submit-uploaded-file'
      type: regular
      version: -1
    taskid: 5a968f27-55f8-4761-88d0-a89b4d023bda
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1075
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 790,
        "x": 50,
        "y": 20
      }
    }
  }
