contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.1.25
    packID: Carbon_Black_Enterprise_Response
    packName: Carbon Black Enterprise Response
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Carbon Black Response - isolate an endpoint, given a hostname.
id: block_endpoint_-_carbon_black_response
inputs:
- description: The hostname to isolate.
  key: Hostname
  playbookInputQuery: null
  required: false
  value:
    simple: ${Endpoint.Hostname}
name: Block Endpoint - Carbon Black Response
outputs:
- contextPath: CbResponse.Sensors.CbSensorID
  description: Carbon Black Response Sensors ids that has been isolated.
- contextPath: Endpoint
  description: The isolated enpoint.
- contextPath: CbResponse.Sensors.Status
  description: Sensor status.
  type: unknown
- contextPath: CbResponse.Sensors.Isolated
  description: Is sensor isolated.
  type: unknown
- contextPath: Endpoint.Hostname
  description: Endpoint hostname.
  type: unknown
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 73040a0e-cca5-4197-8089-f46650317040
      iscommand: false
      name: ""
      version: -1
    taskid: 73040a0e-cca5-4197-8089-f46650317040
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: carbonblack
      description: Query  Carbon Black Enterprise Response for the host
      id: 81cfb3e4-cb04-4c91-8bc7-d23980939d7e
      iscommand: true
      name: Get host information from Carbon Black Enterprise Response
      script: carbonblack|||cb-sensor-info
      type: regular
      version: -1
    taskid: 81cfb3e4-cb04-4c91-8bc7-d23980939d7e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 380
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      sensor:
        simple: ${CbResponse.Sensors.CbSensorID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: carbonblack
      description: Carbon Black Response - isolate the host
      id: 36d3a39d-ae26-4db6-8ed5-228172276852
      iscommand: true
      name: Isolate hostname
      script: carbonblack|||cb-quarantine-device
      type: regular
      version: -1
    taskid: 36d3a39d-ae26-4db6-8ed5-228172276852
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 585
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d35be2d6-6709-40d0-846e-dc9aef142e30
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d35be2d6-6709-40d0-846e-dc9aef142e30
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 960
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: brand
                    operator: isEqualString
                    right:
                      value:
                        simple: carbonblack
                - - left:
                      iscontext: true
                      value:
                        simple: state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if Carbon black active in the system.
      id: 27405cc3-bf4c-4879-87ad-880b99941e9a
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      type: condition
      version: -1
    taskid: 27405cc3-bf4c-4879-87ad-880b99941e9a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 210
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: carbonblack
      description: Query  Carbon Black Enterprise Response for the host
      id: 5c297191-5859-4f5a-8d26-f5f1818c00aa
      iscommand: true
      name: Get host information from Carbon Black Enterprise Response
      script: carbonblack|||cb-sensor-info
      type: regular
      version: -1
    taskid: 5c297191-5859-4f5a-8d26-f5f1818c00aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -180,
          "y": 785
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 975,
        "width": 722.5,
        "x": -180,
        "y": 50
      }
    }
  }
